baseURL = "https://irofull.pages.dev/"
languageCode = "ja"
title = "イロフル"
theme = "PaperMod"

[params]
  author = "irofull"
  description = "人生のあれこれを、色とりどりに。"

[params.homeInfoParams]
  Title = "イロフル / irofull"
  Content = "人生のあれこれを、色とりどりに。\n\n暮らし　なぜだろう　ずっと考えてること　気づき　好きなこと（旅行・編み物・食べ物 etc…)\n\n*Colorful Stories from Everyday Life — big questions, small joys, everything in between.*"

[menu]
  [[menu.main]]
    name = "ホーム"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "記事一覧"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
